import edu.rit.ds.RemoteEvent;

/**
 * Class JobEvent object is used to be passed along an even  generated by JobScheduler in the
 * JobScheduler system. The Job events are used to report the lifetime of the Job
 * in the GC system.
 * 
 * @author Alan Kaminsky
 * 
 * @author Roshan Balaji
 */
public class JobEvent
	extends RemoteEvent 
	{
	public  String serverID;
	public  JobRef job;
	int state=0;
	public String server=null;
	/**
	 * Create a new Jobevent.
	 *
	 * @param  _job  jobRef the job whose life detail are going to be logged.
	 * 
	 */
	public JobEvent
		(
		 JobRef _job)
		{
		this.job=_job;
		}
	/**
	 * Create a new node event.
	 *
	 * @param  _job  jobRef the job whose life detail are going to be logged.
	 * 
	 * @param _state int the state variable is used to identify the kind of notification
	 * i.e if it is a schedule notification or a start or finish notification.
	 * 
	 * @param _server ComputeServerInterface it gives the information on the sever that 
	 * is processing the job.
	 */
	public JobEvent
	(int _state,String _server,
	 JobRef _job)
	{
	this.state=_state;
	this.server=_server;
	this.job=_job;
	}
	}